# Generated by Django 4.2.5 on 2023-11-08 04:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='игра')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Мы деньги за игры не даём!')], verbose_name='цена')),
                ('poster', models.ImageField(upload_to='posters', verbose_name='постер')),
                ('rate', models.FloatField(max_length=5, verbose_name='рейтинг')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыта ли')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_finished', models.DateField(default=datetime.datetime(2023, 12, 8, 10, 42, 16, 339891), verbose_name='Дата завершения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('id',),
            },
        ),
    ]
